feat: added cancel for ux
mintware-de/flutter_barcode_reader pull request #198
Opened 2020-03-24 12:57 UTC by iRaySpace

2020-04-12 12:27 UTC, devtronic commented
Thanks for contributing 🙂

Please merge the current master branch in your branch. 
I also added few notes to your changes

2020-04-14 11:16 UTC, devtronic requested changes

2020-04-14 11:16 UTC, devtronic commented on android/src/main/kotlin/de/mintware/barcode_scan/BarcodeScannerActivity.kt
> +        val item = menu.add(0, CANCEL, 0, "Cancel")
Use `config.stringsMap["cancel"]` instead of "Cancel"

2020-04-14 11:16 UTC, devtronic commented on android/src/main/kotlin/de/mintware/barcode_scan/BarcodeScannerActivity.kt
> +            finish()
call `setResult(RESULT_CANCELED)` before `finish()`

2020-04-16 01:59 UTC, iRaySpace commented
Hello, can you help me check?

2020-04-17 06:39 UTC, ccfiel commented
@devtronic when will this merge? :)

2020-04-17 06:48 UTC, devtronic commented
I'll review the changes today

2020-04-17 10:22 UTC, ccfiel commented
@devtronic thanks for the update 😊

2020-04-17 16:14 UTC, devtronic requested changes

2020-04-17 16:14 UTC, devtronic commented on android/src/main/kotlin/de/mintware/barcode_scan/BarcodeScannerActivity.kt
> +        val item = menu.add(0, CANCEL, 0, config.stringsMap["cancel"])
Duplicate declaration of the item variable. Rename this to `cancelButton` and the one above `flashButton`

2020-04-18 11:17 UTC, devtronic commented
@iRaySpace I can't build the project since there is a variable getting defined twice. I added a comment on the corresponding line in the `BarcodeScannerActivity.kt`. After you fixed that I'll merge the PR.

2020-04-19 14:11 UTC, iRaySpace commented
Hello @devtronic Thank you, and also I have put up the changes.

2020-04-20 20:50 UTC, devtronic approved these changes

2020-04-20 20:51 UTC, merged